### PR TITLE
Add testing for Ruby 2.4.1

### PR DESCRIPTION
**Pull request by thomasriley**
## Pull Request Checklist

sensu-plugins/sensu-plugins-feature-requests#27

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose
Add Travis testing for Ruby 2.4.1

### CODE REVIEW

**Comment by majormoses** [comment]
@thomasriley thanks for this I will take a look.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
merged and updated the list, thanks again.

**Comment by mbbroberg** [comment]
This is so dope 👏 👏 👏 . Great to have you here @thomasriley!

**Comment by thomasriley** [comment]
@mbbroberg happy to help :)

**Pull request merged**
